# Complete Tensor Tutorial - From Basics to Mastery

## What are Tensors?

Tensors are **multi-dimensional arrays** that are the fundamental data structure in deep learning. Think of them as:
- **Scalar (0D tensor)**: Single number (e.g., 5)
- **Vector (1D tensor)**: Array of numbers (e.g., [1, 2, 3])
- **Matrix (2D tensor)**: Grid of numbers (e.g., [[1, 2], [3, 4]])
- **Higher-dimensional tensors**: 3D, 4D, 5D, etc.

Tensors are used to represent:
- Images (3D: height × width × color channels)
- Videos (4D: time × height × width × color channels)
- Batches of data (additional dimension for batch size)
- Neural network weights and activations

## Why PyTorch?
We'll use PyTorch - the most popular deep learning framework with excellent tensor operations.

# Install PyTorch (if not already installed)
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.10.0+cpu
CUDA available: False


# 1. Creating Tensors

## Different Ways to Create Tensors

In [2]:
# Method 1: From Python lists
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("From list:", tensor_from_list)

# Method 2: From nested lists (creates 2D tensor)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("2D tensor:\n", tensor_2d)

# Method 3: Zeros tensor
zeros = torch.zeros(3, 4)
print("Zeros (3x4):\n", zeros)

# Method 4: Ones tensor
ones = torch.ones(2, 3)
print("Ones (2x3):\n", ones)

# Method 5: Random values (uniform distribution between 0 and 1)
random_uniform = torch.rand(2, 3)
print("Random uniform (2x3):\n", random_uniform)

# Method 6: Random values (normal distribution)
random_normal = torch.randn(2, 3)
print("Random normal (2x3):\n", random_normal)

From list: tensor([1, 2, 3, 4])
2D tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Zeros (3x4):
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones (2x3):
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random uniform (2x3):
 tensor([[0.7396, 0.5368, 0.1457],
        [0.6897, 0.1591, 0.2562]])
Random normal (2x3):
 tensor([[-1.5909,  0.3756, -0.7958],
        [-2.5651,  0.4223, -0.0501]])


In [3]:
# Method 7: Range of values (like Python's range)
range_tensor = torch.arange(0, 10, 2)  # start, end (exclusive), step
print("Arange:", range_tensor)

# Method 8: Linearly spaced values
linspace = torch.linspace(0, 10, 5)  # start, end, number of points
print("Linspace:", linspace)

# Method 9: Eye matrix (identity matrix)
eye = torch.eye(3)
print("Eye matrix (3x3):\n", eye)

# Method 10: Empty tensor (uninitialized values - faster but contains garbage)
empty = torch.empty(2, 3)
print("Empty (2x3) - contains uninitialized values:\n", empty)

Arange: tensor([0, 2, 4, 6, 8])
Linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Eye matrix (3x3):
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Empty (2x3) - contains uninitialized values:
 tensor([[3.1093e+00, 0.0000e+00, 3.5193e+00],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])


In [4]:
# Method 11: From NumPy arrays
numpy_array = np.array([1, 2, 3, 4])
tensor_from_numpy = torch.from_numpy(numpy_array)
print("From NumPy:", tensor_from_numpy)

# Method 12: Specifying dtype (data type)
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
int_tensor = torch.tensor([1.5, 2.7, 3.9], dtype=torch.int32)
print("Float tensor:", float_tensor)
print("Int tensor:", int_tensor)

# Method 13: Like another tensor (same shape and type)
like_tensor = torch.ones_like(tensor_2d)
print("Ones like tensor_2d:\n", like_tensor)

# Method 14: Full tensor (fill with specific value)
full_tensor = torch.full((2, 3), 7)
print("Full (2x3) filled with 7:\n", full_tensor)

From NumPy: tensor([1, 2, 3, 4])
Float tensor: tensor([1., 2., 3.])
Int tensor: tensor([1, 2, 3], dtype=torch.int32)
Ones like tensor_2d:
 tensor([[1, 1, 1],
        [1, 1, 1]])
Full (2x3) filled with 7:
 tensor([[7, 7, 7],
        [7, 7, 7]])


# 2. Tensor Properties

Understanding tensor properties is crucial for debugging and tensor operations.

In [5]:
# Create a sample tensor
x = torch.randn(3, 4, 5)  # 3D tensor: 3 × 4 × 5

print("Tensor x:", x)
print("\n--- Tensor Properties ---")

# Shape: dimensions of the tensor
print(f"Shape: {x.shape}")  # or x.size()

# Number of dimensions (rank)
print(f"Number of dimensions (ndim): {x.ndim}")

# Total number of elements
print(f"Number of elements: {x.numel()}")

# Data type
print(f"Data type (dtype): {x.dtype}")

# Device (CPU or GPU)
print(f"Device: {x.device}")

# Memory layout
print(f"Memory layout: {x.layout}")

Tensor x: tensor([[[ 4.9044e-01, -1.0140e+00, -4.3617e-01,  1.5898e+00, -1.5561e+00],
         [ 2.6436e+00,  1.2672e-01, -4.2677e-02, -1.5507e+00, -3.6214e-02],
         [-6.2871e-01,  2.9294e-02, -1.0756e-01,  3.9290e-01,  1.3645e+00],
         [-1.0750e+00, -1.4733e+00,  1.8415e+00, -1.5135e+00,  1.1301e+00]],

        [[-5.6443e-01, -5.6801e-01, -1.0172e+00,  6.7442e-01,  5.5119e-01],
         [ 3.5437e-01,  2.2630e+00, -7.6825e-01,  2.9314e-01, -1.1093e+00],
         [-1.6534e+00,  1.0047e-03,  1.6070e+00,  2.9441e+00,  6.0816e-01],
         [-7.8083e-01,  3.5454e-01,  8.5387e-01,  1.5652e+00,  1.2161e+00]],

        [[-8.1407e-01, -5.1559e-03,  3.2337e-01,  7.1503e-01,  1.4059e-01],
         [ 3.4690e-01, -1.3807e-01,  3.2186e-01,  3.9783e-01,  4.7568e-01],
         [ 1.0745e+00, -2.1854e-01, -1.5277e+00, -1.6868e-01,  1.0345e+00],
         [ 8.4628e-01,  1.6495e-01,  1.7960e+00,  2.4428e-02,  1.4855e+00]]])

--- Tensor Properties ---
Shape: torch.Size([3, 4, 5])
Number of dimens

In [6]:
# Common data types in PyTorch
print("Common data types:")
print(f"float32: {torch.float32}")
print(f"float64: {torch.float64}")
print(f"int32: {torch.int32}")
print(f"int64: {torch.int64}")
print(f"bool: {torch.bool}")

# Creating tensors with specific dtypes
tensor_float32 = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor_float64 = torch.tensor([1, 2, 3], dtype=torch.float64)
tensor_int32 = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_int64 = torch.tensor([1, 2, 3], dtype=torch.int64)

print(f"\nFloat32 tensor: {tensor_float32.dtype}")
print(f"Float64 tensor: {tensor_float64.dtype}")
print(f"Int32 tensor: {tensor_int32.dtype}")
print(f"Int64 tensor: {tensor_int64.dtype}")

Common data types:
float32: torch.float32
float64: torch.float64
int32: torch.int32
int64: torch.int64
bool: torch.bool

Float32 tensor: torch.float32
Float64 tensor: torch.float64
Int32 tensor: torch.int32
Int64 tensor: torch.int64


# 3. Basic Tensor Operations

## Arithmetic Operations

In [7]:
# Create two tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

print("a =", a)
print("b =", b)

# Addition
print("\n--- Addition ---")
print("a + b =", a + b)
print("torch.add(a, b) =", torch.add(a, b))
print("a.add(b) =", a.add(b))  # In-place operation

# Subtraction
print("\n--- Subtraction ---")
print("a - b =", a - b)
print("torch.sub(a, b) =", torch.sub(a, b))

# Multiplication (element-wise)
print("\n--- Element-wise Multiplication ---")
print("a * b =", a * b)
print("torch.mul(a, b) =", torch.mul(a, b))

# Division (element-wise)
print("\n--- Element-wise Division ---")
print("a / b =", a / b)
print("torch.div(a, b) =", torch.div(a, b))

a = tensor([1, 2, 3, 4])
b = tensor([5, 6, 7, 8])

--- Addition ---
a + b = tensor([ 6,  8, 10, 12])
torch.add(a, b) = tensor([ 6,  8, 10, 12])
a.add(b) = tensor([ 6,  8, 10, 12])

--- Subtraction ---
a - b = tensor([-4, -4, -4, -4])
torch.sub(a, b) = tensor([-4, -4, -4, -4])

--- Element-wise Multiplication ---
a * b = tensor([ 5, 12, 21, 32])
torch.mul(a, b) = tensor([ 5, 12, 21, 32])

--- Element-wise Division ---
a / b = tensor([0.2000, 0.3333, 0.4286, 0.5000])
torch.div(a, b) = tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [8]:
# Scalar operations
a = torch.tensor([1, 2, 3, 4])

print("a =", a)
print("a + 10 =", a + 10)
print("a - 5 =", a - 5)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a ** 2 =", a ** 2)  # Power
print("a % 3 =", a % 3)  # Modulo

a = tensor([1, 2, 3, 4])
a + 10 = tensor([11, 12, 13, 14])
a - 5 = tensor([-4, -3, -2, -1])
a * 2 = tensor([2, 4, 6, 8])
a / 2 = tensor([0.5000, 1.0000, 1.5000, 2.0000])
a ** 2 = tensor([ 1,  4,  9, 16])
a % 3 = tensor([1, 2, 0, 1])


In [9]:
# In-place operations (modify the tensor directly)
a = torch.tensor([1, 2, 3, 4])
print("Original a =", a)

# In-place operations have underscore suffix
a.add_(10)  # Equivalent to a = a + 10
print("After a.add_(10):", a)

a.mul_(2)  # Equivalent to a = a * 2
print("After a.mul_(2):", a)

a.sub_(5)  # Equivalent to a = a - 5
print("After a.sub_(5):", a)

Original a = tensor([1, 2, 3, 4])
After a.add_(10): tensor([11, 12, 13, 14])
After a.mul_(2): tensor([22, 24, 26, 28])
After a.sub_(5): tensor([17, 19, 21, 23])


# 4. Matrix Operations

These are crucial for linear algebra and neural networks.

In [10]:
# Matrix multiplication (dot product)
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

print("A =\n", A)
print("B =\n", B)

# Matrix multiplication (dot product)
print("\n--- Matrix Multiplication ---")
print("A @ B =\n", A @ B)  # Python 3.5+ syntax
print("torch.matmul(A, B) =\n", torch.matmul(A, B))
print("torch.mm(A, B) =\n", torch.mm(A, B))  # Only for 2D tensors

A =
 tensor([[1, 2],
        [3, 4]])
B =
 tensor([[5, 6],
        [7, 8]])

--- Matrix Multiplication ---
A @ B =
 tensor([[19, 22],
        [43, 50]])
torch.matmul(A, B) =
 tensor([[19, 22],
        [43, 50]])
torch.mm(A, B) =
 tensor([[19, 22],
        [43, 50]])


In [11]:
# Transpose
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("A =\n", A)
print("A.T (transpose) =\n", A.T)
print("torch.transpose(A, 0, 1) =\n", torch.transpose(A, 0, 1))

# For higher dimensional tensors
B = torch.randn(2, 3, 4)
print(f"\nB shape: {B.shape}")
print(f"transpose B shape: {torch.transpose(B, 0, 2).shape}")

A =
 tensor([[1, 2, 3],
        [4, 5, 6]])
A.T (transpose) =
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.transpose(A, 0, 1) =
 tensor([[1, 4],
        [2, 5],
        [3, 6]])

B shape: torch.Size([2, 3, 4])
transpose B shape: torch.Size([4, 3, 2])


In [13]:
# Other important matrix operations
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

print("A =\n", A)

# Matrix inverse (must be square)
print("\n--- Matrix Inverse ---")
print("torch.inverse(A) =\n", torch.inverse(A))

# Matrix determinant
print("\n--- Matrix Determinant ---")
print("torch.det(A) =", torch.det(A))

# Matrix trace (sum of diagonal elements)
print("\n--- Matrix Trace ---")
print("torch.trace(A) =", torch.trace(A))

# Diagonal elements
print("\n--- Diagonal ---")
print("torch.diag(A) =", torch.diag(A))

A =
 tensor([[1., 2.],
        [3., 4.]])

--- Matrix Inverse ---
torch.inverse(A) =
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

--- Matrix Determinant ---
torch.det(A) = tensor(-2.)

--- Matrix Trace ---
torch.trace(A) = tensor(5.)

--- Diagonal ---
torch.diag(A) = tensor([1., 4.])


# 5. Aggregation Operations

Reduce tensors to scalars or smaller tensors.

In [15]:
# Add dtype=torch.float32 to fix the error
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)

print("x =\n", x)

# Now these will work perfectly:
print("\n--- Mean ---")
print("x.mean() =", x.mean())
print("x.mean(dim=0) =", x.mean(dim=0))
print("x.mean(dim=1) =", x.mean(dim=1))

print("\n--- Standard Deviation ---")
print("x.std() =", x.std())


x =
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

--- Mean ---
x.mean() = tensor(5.)
x.mean(dim=0) = tensor([4., 5., 6.])
x.mean(dim=1) = tensor([2., 5., 8.])

--- Standard Deviation ---
x.std() = tensor(2.7386)


In [16]:
# Min and Max
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("x =\n", x)

print("\n--- Min ---")
print("x.min() =", x.min())
print("x.min(dim=0) =", x.min(dim=0))  # Returns (values, indices)
min_values, min_indices = x.min(dim=0)
print("Min values:", min_values)
print("Min indices:", min_indices)

print("\n--- Max ---")
print("x.max() =", x.max())
print("x.max(dim=1) =", x.max(dim=1))
max_values, max_indices = x.max(dim=1)
print("Max values:", max_values)
print("Max indices:", max_indices)

x =
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

--- Min ---
x.min() = tensor(1)
x.min(dim=0) = torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))
Min values: tensor([1, 2, 3])
Min indices: tensor([0, 0, 0])

--- Max ---
x.max() = tensor(9)
x.max(dim=1) = torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))
Max values: tensor([3, 6, 9])
Max indices: tensor([2, 2, 2])


In [17]:
# Product (multiplication of all elements)
x = torch.tensor([1, 2, 3, 4])
print("x =", x)
print("x.prod() =", x.prod())

# Argmax and Argmin (index of max/min value)
x = torch.tensor([10, 5, 20, 15, 30])
print("\nx =", x)
print("x.argmax() =", x.argmax())  # Index of maximum value
print("x.argmin() =", x.argmin())  # Index of minimum value

# Cumulative operations
print("\n--- Cumulative Operations ---")
print("x.cumsum(0) =", x.cumsum(0))  # Cumulative sum
print("x.cumprod(0) =", x.cumprod(0))  # Cumulative product

x = tensor([1, 2, 3, 4])
x.prod() = tensor(24)

x = tensor([10,  5, 20, 15, 30])
x.argmax() = tensor(4)
x.argmin() = tensor(1)

--- Cumulative Operations ---
x.cumsum(0) = tensor([10, 15, 35, 50, 80])
x.cumprod(0) = tensor([    10,     50,   1000,  15000, 450000])


# 6. Reshaping Tensors

Reshaping is one of the most common operations in deep learning.

In [18]:
# Reshape vs View - Important Difference!
x = torch.arange(1, 13)  # 12 elements
print("Original x:", x)
print("Shape:", x.shape)

# reshape() - can return a new tensor or a view
reshaped = x.reshape(3, 4)
print("\nReshaped to (3, 4):\n", reshaped)
print("Shape:", reshaped.shape)

# view() - always returns a view (shares memory)
viewed = x.view(3, 4)
print("\nViewed as (3, 4):\n", viewed)
print("Shape:", viewed.shape)

# Modify the view - original tensor changes!
viewed[0, 0] = 999
print("\nAfter modifying viewed[0, 0] = 999:")
print("Original x:", x)  # Notice the change!
print("Viewed:", viewed)

Original x: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Shape: torch.Size([12])

Reshaped to (3, 4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape: torch.Size([3, 4])

Viewed as (3, 4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape: torch.Size([3, 4])

After modifying viewed[0, 0] = 999:
Original x: tensor([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
Viewed: tensor([[999,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])


In [19]:
# Flatten - convert multi-dimensional to 1D
x = torch.randn(2, 3, 4)
print("Original shape:", x.shape)

# Method 1: flatten()
flattened = x.flatten()
print("Flattened shape:", flattened.shape)

# Method 2: reshape(-1)
flattened2 = x.reshape(-1)
print("Reshaped to -1:", flattened2.shape)

# Flatten specific dimensions
flatten_start_dim = x.flatten(start_dim=1)  # Flatten from dim 1 onwards
print("Flatten from dim 1:", flatten_start_dim.shape)

Original shape: torch.Size([2, 3, 4])
Flattened shape: torch.Size([24])
Reshaped to -1: torch.Size([24])
Flatten from dim 1: torch.Size([2, 12])


In [20]:
# Squeeze and Unsqueeze - Add/Remove dimensions of size 1
x = torch.randn(2, 1, 3, 1, 4)
print("Original shape:", x.shape)

# Squeeze - remove dimensions of size 1
squeezed = x.squeeze()
print("After squeeze():", squeezed.shape)

# Squeeze specific dimension
squeezed_dim = x.squeeze(dim=1)
print("After squeeze(dim=1):", squeezed_dim.shape)

# Unsqueeze - add dimension of size 1 at specified position
x = torch.randn(2, 3)
print("\nOriginal shape:", x.shape)

unsqueezed = x.unsqueeze(dim=0)  # Add dimension at position 0
print("After unsqueeze(dim=0):", unsqueezed.shape)

unsqueezed_last = x.unsqueeze(dim=-1)  # Add dimension at last position
print("After unsqueeze(dim=-1):", unsqueezed_last.shape)

Original shape: torch.Size([2, 1, 3, 1, 4])
After squeeze(): torch.Size([2, 3, 4])
After squeeze(dim=1): torch.Size([2, 3, 1, 4])

Original shape: torch.Size([2, 3])
After unsqueeze(dim=0): torch.Size([1, 2, 3])
After unsqueeze(dim=-1): torch.Size([2, 3, 1])


In [21]:
# Permute - Rearrange dimensions (transpose for higher dimensions)
x = torch.randn(2, 3, 4)
print("Original shape:", x.shape)

# Permute dimensions: (0, 1, 2) -> (2, 1, 0)
permuted = x.permute(2, 1, 0)
print("After permute(2, 1, 0):", permuted.shape)

# Common use case: Changing image format from (batch, height, width, channels) to (batch, channels, height, width)
x = torch.randn(32, 224, 224, 3)  # NHWC format
print("\nNHWC format:", x.shape)
x_nchw = x.permute(0, 3, 1, 2)  # Convert to NCHW format
print("NCHW format:", x_nchw.shape)

Original shape: torch.Size([2, 3, 4])
After permute(2, 1, 0): torch.Size([4, 3, 2])

NHWC format: torch.Size([32, 224, 224, 3])
NCHW format: torch.Size([32, 3, 224, 224])


In [22]:
# Transpose vs Permute
x = torch.randn(2, 3, 4)
print("Original shape:", x.shape)

# transpose() swaps two dimensions
transposed = x.transpose(0, 1)  # Swap dim 0 and dim 1
print("After transpose(0, 1):", transposed.shape)

# transpose(0, 1) is equivalent to permute(1, 0, 2)
permuted = x.permute(1, 0, 2)
print("After permute(1, 0, 2):", permuted.shape)

# They produce the same result
print("Are they equal?", transposed.shape == permuted.shape)

Original shape: torch.Size([2, 3, 4])
After transpose(0, 1): torch.Size([3, 2, 4])
After permute(1, 0, 2): torch.Size([3, 2, 4])
Are they equal? True


# 7. Broadcasting

Broadcasting allows operations on tensors of different shapes by automatically expanding dimensions.

In [23]:
# Broadcasting Rule 1: Tensor with fewer dimensions is prepended with dimensions of size 1
x = torch.tensor([1, 2, 3])  # Shape: (3,)
y = torch.tensor([[4], [5]])  # Shape: (2, 1)

print("x shape:", x.shape)
print("y shape:", y.shape)

result = x + y
print("\nx + y shape:", result.shape)
print("Result:\n", result)

# What happened?
# x: (3,) -> (1, 1, 3) -> (2, 1, 3)
# y: (2, 1) -> (2, 1, 1) -> (2, 1, 3)
# Result: (2, 1, 3)

x shape: torch.Size([3])
y shape: torch.Size([2, 1])

x + y shape: torch.Size([2, 3])
Result:
 tensor([[5, 6, 7],
        [6, 7, 8]])


In [24]:
# Broadcasting Rule 2: Dimensions of size 1 are expanded to match the other tensor
x = torch.randn(3, 1)  # Shape: (3, 1)
y = torch.randn(1, 4)  # Shape: (1, 4)

print("x shape:", x.shape)
print("y shape:", y.shape)

result = x + y
print("\nx + y shape:", result.shape)
print("Result:\n", result)

# What happened?
# x: (3, 1) -> (3, 4) by replicating columns
# y: (1, 4) -> (3, 4) by replicating rows
# Result: (3, 4)

x shape: torch.Size([3, 1])
y shape: torch.Size([1, 4])

x + y shape: torch.Size([3, 4])
Result:
 tensor([[-0.6594, -2.1120, -1.1474, -3.0853],
        [-0.3112, -1.7638, -0.7992, -2.7370],
        [ 1.1001, -0.3525,  0.6121, -1.3257]])


In [25]:
# Broadcasting Rule 3: All other dimensions must match or be 1
x = torch.randn(2, 3, 4)  # Shape: (2, 3, 4)
y = torch.randn(3, 1)     # Shape: (3, 1)

print("x shape:", x.shape)
print("y shape:", y.shape)

result = x + y
print("\nx + y shape:", result.shape)

# What happened?
# y: (3, 1) -> (1, 3, 1) -> (2, 3, 4)
# Result: (2, 3, 4)

# This works because:
# - dim 0: 2 vs 1 (1 can expand to 2)
# - dim 1: 3 vs 3 (match)
# - dim 2: 4 vs 1 (1 can expand to 4)

x shape: torch.Size([2, 3, 4])
y shape: torch.Size([3, 1])

x + y shape: torch.Size([2, 3, 4])


In [26]:
# Broadcasting failure example
x = torch.randn(2, 3)
y = torch.randn(3, 4)

print("x shape:", x.shape)
print("y shape:", y.shape)

try:
    result = x + y
    print("Result shape:", result.shape)
except RuntimeError as e:
    print("Error:", e)
    print("This fails because dimensions don't match and neither is 1")

x shape: torch.Size([2, 3])
y shape: torch.Size([3, 4])
Error: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
This fails because dimensions don't match and neither is 1


# 8. Indexing and Slicing

Access and modify specific elements or sub-tensors.

In [28]:
import torch

# 1D tensor indexing
x = torch.arange(10)
print("x =", x)

print("\n--- Basic Indexing ---")
print(f"x[0] = {x[0].item()}")      # .item() gets the actual number out of the 0D tensor
print(f"x[-1] = {x[-1].item()}")    # Last element
print(f"x[2:5] = {x[2:5]}")         # Slice from index 2 to 4 (5 is exclusive)
print(f"x[:5] = {x[:5]}")           # First 5 elements
print(f"x[5:] = {x[5:]}")           # Elements from index 5 onwards
print(f"x[::2] = {x[::2]}")         # Every second element (Step size 2)

# REVERSING: Use torch.flip for the most reliable behavior
print(f"x reversed = {torch.flip(x, dims=[0])}") 


x = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

--- Basic Indexing ---
x[0] = 0
x[-1] = 9
x[2:5] = tensor([2, 3, 4])
x[:5] = tensor([0, 1, 2, 3, 4])
x[5:] = tensor([5, 6, 7, 8, 9])
x[::2] = tensor([0, 2, 4, 6, 8])
x reversed = tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [29]:
# 2D tensor indexing
x = torch.arange(12).reshape(3, 4)
print("x =\n", x)

print("\n--- Row and Column Access ---")
print("x[0] =", x[0])  # First row
print("x[:, 0] =", x[:, 0])  # First column
print("x[1, 2] =", x[1, 2])  # Element at row 1, column 2

print("\n--- Slicing ---")
print("x[0:2, :] =\n", x[0:2, :])  # First 2 rows, all columns
print("x[:, 1:3] =\n", x[:, 1:3])  # All rows, columns 1-2
print("x[1:, 2:] =\n", x[1:, 2:])  # Rows 1+, columns 2+

x =
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

--- Row and Column Access ---
x[0] = tensor([0, 1, 2, 3])
x[:, 0] = tensor([0, 4, 8])
x[1, 2] = tensor(6)

--- Slicing ---
x[0:2, :] =
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
x[:, 1:3] =
 tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])
x[1:, 2:] =
 tensor([[ 6,  7],
        [10, 11]])


In [30]:
# Advanced indexing with lists
x = torch.arange(12).reshape(3, 4)
print("x =\n", x)

print("\n--- Indexing with Lists ---")
print("x[[0, 2]] =\n", x[[0, 2]])  # Rows 0 and 2
print("x[:, [1, 3]] =\n", x[:, [1, 3]])  # Columns 1 and 3

# Indexing with tensors
rows = torch.tensor([0, 2])
cols = torch.tensor([1, 3])
print("x[rows, cols] =", x[rows, cols])  # Elements (0,1) and (2,3)

x =
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

--- Indexing with Lists ---
x[[0, 2]] =
 tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])
x[:, [1, 3]] =
 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
x[rows, cols] = tensor([ 1, 11])


In [31]:
# Boolean indexing (masking)
x = torch.randn(3, 4)
print("x =\n", x)

# Create a boolean mask
mask = x > 0
print("\nMask (x > 0):\n", mask)

# Use mask to select elements
positive_values = x[mask]
print("\nPositive values:", positive_values)

# Set negative values to 0
x[x < 0] = 0
print("\nAfter setting negatives to 0:\n", x)

x =
 tensor([[-5.3485e-04, -9.1856e-01,  4.4663e-01,  1.1828e+00],
        [-8.9932e-01,  1.0719e+00,  1.0529e+00,  1.3173e+00],
        [-4.7455e-01,  8.5997e-03, -1.2434e+00, -3.5813e-01]])

Mask (x > 0):
 tensor([[False, False,  True,  True],
        [False,  True,  True,  True],
        [False,  True, False, False]])

Positive values: tensor([0.4466, 1.1828, 1.0719, 1.0529, 1.3173, 0.0086])

After setting negatives to 0:
 tensor([[0.0000, 0.0000, 0.4466, 1.1828],
        [0.0000, 1.0719, 1.0529, 1.3173],
        [0.0000, 0.0086, 0.0000, 0.0000]])


In [32]:
# Modifying tensors via indexing
x = torch.zeros(3, 4)
print("Original x =\n", x)

# Modify single element
x[0, 0] = 1
print("\nAfter x[0, 0] = 1:\n", x)

# Modify entire row
x[1, :] = 2
print("\nAfter x[1, :] = 2:\n", x)

# Modify entire column
x[:, 2] = 3
print("\nAfter x[:, 2] = 3:\n", x)

# Modify slice
x[2:, 1:3] = 4
print("\nAfter x[2:, 1:3] = 4:\n", x)

Original x =
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

After x[0, 0] = 1:
 tensor([[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

After x[1, :] = 2:
 tensor([[1., 0., 0., 0.],
        [2., 2., 2., 2.],
        [0., 0., 0., 0.]])

After x[:, 2] = 3:
 tensor([[1., 0., 3., 0.],
        [2., 2., 3., 2.],
        [0., 0., 3., 0.]])

After x[2:, 1:3] = 4:
 tensor([[1., 0., 3., 0.],
        [2., 2., 3., 2.],
        [0., 4., 4., 0.]])


# 9. GPU Tensors

Moving tensors to GPU for faster computation (essential for deep learning).

In [4]:
import torch
# Check if CUDA (GPU) is available
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA device count: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    print(f"CUDA device name: {torch.cuda.get_device_name(0)}")
    print(f"Current device: {torch.cuda.current_device()}")

CUDA available: True
CUDA device count: 1
CUDA device name: Tesla T4
Current device: 0


In [6]:
# Create tensor on CPU
x_cpu = torch.randn(1000, 1000)
print(f"Tensor device: {x_cpu.device}")

# Move tensor to GPU (if available)
if torch.cuda.is_available():
    x_gpu = x_cpu.to('cuda')  # or x_cpu.cuda()
    print(f"Tensor device after .to('cuda'): {x_gpu.device}")
    
    # Create tensor directly on GPU
    y_gpu = torch.randn(1000, 1000, device='cuda')
    print(f"Tensor created on GPU: {y_gpu.device}")
    
    # Move back to CPU
    x_back = x_gpu.to('cpu')  # or x_gpu.cpu()
    print(f"Tensor device after .to('cpu'): {x_back.device}")
else:
    print("GPU not available. Using CPU only.")

Tensor device: cpu
Tensor device after .to('cuda'): cuda:0
Tensor created on GPU: cuda:0
Tensor device after .to('cpu'): cpu


In [7]:
# GPU vs CPU performance comparison
import time

if torch.cuda.is_available():
    size = 5000
    
    # CPU computation
    x_cpu = torch.randn(size, size)
    y_cpu = torch.randn(size, size)
    
    start = time.time()
    result_cpu = torch.matmul(x_cpu, y_cpu)
    cpu_time = time.time() - start
    print(f"CPU time: {cpu_time:.4f} seconds")
    
    # GPU computation
    x_gpu = x_cpu.to('cuda')
    y_gpu = y_cpu.to('cuda')
    
    # Warm up GPU
    _ = torch.matmul(x_gpu, y_gpu)
    torch.cuda.synchronize()
    
    start = time.time()
    result_gpu = torch.matmul(x_gpu, y_gpu)
    torch.cuda.synchronize()
    gpu_time = time.time() - start
    print(f"GPU time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.2f}x")
else:
    print("GPU not available for performance comparison")

CPU time: 1.8893 seconds
GPU time: 0.0785 seconds
Speedup: 24.06x


# 10. Automatic Differentiation (Autograd)

PyTorch's autograd engine automatically computes gradients - essential for training neural networks.

In [8]:
# Create a tensor with gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)
print("Tensor with requires_grad=True:", x)
print("requires_grad:", x.requires_grad)

# Perform operations
y = x + 2
z = y * y * 3
out = z.mean()

print("\n--- Computation Graph ---")
print("y = x + 2:", y)
print("z = y * y * 3:", z)
print("out = z.mean():", out)

# Compute gradients
out.backward()

print("\n--- Gradients ---")
print("x.grad:", x.grad)

Tensor with requires_grad=True: tensor([2., 3.], requires_grad=True)
requires_grad: True

--- Computation Graph ---
y = x + 2: tensor([4., 5.], grad_fn=<AddBackward0>)
z = y * y * 3: tensor([48., 75.], grad_fn=<MulBackward0>)
out = z.mean(): tensor(61.5000, grad_fn=<MeanBackward0>)

--- Gradients ---
x.grad: tensor([12., 15.])


In [9]:
# Understanding the gradient computation
# Let's manually verify: y = x + 2, z = 3*y^2, out = mean(z)
# dz/dx = dz/dy * dy/dx = 6*y * 1 = 6*y
# dout/dx = (1/2) * dz/dx = 3*y

x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x + 2  # y = [4, 5]
z = y * y * 3  # z = [48, 75]
out = z.mean()  # out = (48 + 75) / 2 = 61.5

out.backward()

print("x:", x)
print("y:", y)
print("Manual gradient calculation:")
print("For x=2: y=4, gradient = 3*4 = 12")
print("For x=3: y=5, gradient = 3*5 = 15")
print("Actual gradient:", x.grad)

x: tensor([2., 3.], requires_grad=True)
y: tensor([4., 5.], grad_fn=<AddBackward0>)
Manual gradient calculation:
For x=2: y=4, gradient = 3*4 = 12
For x=3: y=5, gradient = 3*5 = 15
Actual gradient: tensor([12., 15.])


In [10]:
# Disabling gradient tracking (for inference)
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x + 2

print("With gradient tracking:")
print("y.requires_grad:", y.requires_grad)

# Method 1: torch.no_grad()
with torch.no_grad():
    z = x + 2
print("With torch.no_grad():")
print("z.requires_grad:", z.requires_grad)

# Method 2: detach()
w = x.detach() + 2
print("With detach():")
print("w.requires_grad:", w.requires_grad)

With gradient tracking:
y.requires_grad: True
With torch.no_grad():
z.requires_grad: False
With detach():
w.requires_grad: False


In [11]:
# Gradient accumulation and zeroing
x = torch.tensor([2.0], requires_grad=True)

# First computation
y = x * 2
y.backward()
print("After first backward:", x.grad)

# Second computation (gradients accumulate!)
y = x * 3
y.backward()
print("After second backward (accumulated):", x.grad)

# Zero gradients
x.grad.zero_()
print("After zero_grad():", x.grad)

After first backward: tensor([2.])
After second backward (accumulated): tensor([5.])
After zero_grad(): tensor([0.])


# 11. Practical Examples

Real-world tensor operations for common tasks.

In [12]:
# Example 1: Normalizing data (common in ML)
data = torch.randn(100, 5)  # 100 samples, 5 features
print("Original data shape:", data.shape)
print("Original mean:", data.mean(dim=0))
print("Original std:", data.std(dim=0))

# Z-score normalization
mean = data.mean(dim=0, keepdim=True)
std = data.std(dim=0, keepdim=True)
normalized = (data - mean) / std

print("\nNormalized data mean:", normalized.mean(dim=0))
print("Normalized data std:", normalized.std(dim=0))

Original data shape: torch.Size([100, 5])
Original mean: tensor([0.0096, 0.1470, 0.0040, 0.0550, 0.0485])
Original std: tensor([0.9694, 1.0736, 1.0132, 1.0443, 0.8835])

Normalized data mean: tensor([-1.7881e-09,  4.7684e-09,  0.0000e+00,  2.0266e-08,  4.7684e-09])
Normalized data std: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [13]:
# Example 2: One-hot encoding
labels = torch.tensor([0, 2, 1, 0, 2])
num_classes = 3

# Method 1: Using scatter_
one_hot = torch.zeros(labels.size(0), num_classes)
one_hot.scatter_(1, labels.unsqueeze(1), 1)
print("One-hot encoded:\n", one_hot)

# Method 2: Using F.one_hot (requires torch.nn.functional)
import torch.nn.functional as F
one_hot2 = F.one_hot(labels, num_classes=num_classes)
print("\nOne-hot encoded (F.one_hot):\n", one_hot2)

One-hot encoded:
 tensor([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

One-hot encoded (F.one_hot):
 tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])


In [14]:
# Example 3: Batch processing
# Simulate a batch of images
batch_size = 32
height, width, channels = 224, 224, 3

# Create random batch (NHWC format)
images = torch.randn(batch_size, height, width, channels)
print("Batch shape (NHWC):", images.shape)

# Convert to NCHW format (preferred by PyTorch)
images_nchw = images.permute(0, 3, 1, 2)
print("Batch shape (NCHW):", images_nchw.shape)

# Normalize pixel values from [0, 1] to [-1, 1]
images_normalized = (images_nchw * 2) - 1
print("Normalized range:", images_normalized.min().item(), "to", images_normalized.max().item())

Batch shape (NHWC): torch.Size([32, 224, 224, 3])
Batch shape (NCHW): torch.Size([32, 3, 224, 224])
Normalized range: -11.791604995727539 to 9.26435375213623


In [15]:
# Example 4: Softmax activation
logits = torch.randn(5, 10)  # 5 samples, 10 classes
print("Logits:\n", logits)

# Softmax along class dimension
softmax = torch.softmax(logits, dim=1)
print("\nSoftmax probabilities:\n", softmax)
print("Sum of probabilities (should be 1):", softmax.sum(dim=1))

Logits:
 tensor([[-2.1914e-01,  4.8998e-01, -1.1261e+00,  3.1247e-01, -8.4518e-01,
         -1.3845e+00, -2.0428e-01,  9.3196e-01, -6.0744e-01, -2.5687e+00],
        [-1.0204e+00,  1.4424e+00,  2.2258e-01, -2.7660e-01,  4.3970e-01,
          4.4872e-01,  6.4281e-02,  4.9088e-01, -1.6175e+00,  1.8080e+00],
        [-6.1792e-01, -6.5307e-01, -1.4872e-01,  9.0779e-01, -5.6045e-01,
         -1.1750e+00, -1.9134e+00, -4.1503e-01, -1.2701e+00,  1.8406e+00],
        [ 1.4230e+00,  3.3541e-01,  9.5254e-02,  7.5585e-01,  2.2726e-04,
         -2.2740e+00,  1.3689e-01,  5.2320e-01,  1.3504e-03,  2.1178e-01],
        [ 4.8530e-01, -5.4641e-02, -2.2460e-01, -9.7263e-01,  2.2211e-01,
          7.5198e-01,  1.0107e-01, -7.1326e-01, -1.3261e+00, -6.0370e-01]])

Softmax probabilities:
 tensor([[0.0915, 0.1859, 0.0369, 0.1556, 0.0489, 0.0285, 0.0928, 0.2891, 0.0620,
         0.0087],
        [0.0193, 0.2261, 0.0668, 0.0405, 0.0829, 0.0837, 0.0570, 0.0873, 0.0106,
         0.3259],
        [0.0425, 0.041

In [16]:
# Example 5: Cosine similarity
a = torch.randn(3, 128)  # 3 vectors of dimension 128
b = torch.randn(3, 128)

# Cosine similarity = (a · b) / (||a|| * ||b||)
dot_product = (a * b).sum(dim=1)
norm_a = torch.norm(a, dim=1)
norm_b = torch.norm(b, dim=1)
cosine_similarity = dot_product / (norm_a * norm_b)

print("Cosine similarities:", cosine_similarity)

# Using built-in function
cos_sim = torch.nn.functional.cosine_similarity(a, b, dim=1)
print("Using F.cosine_similarity:", cos_sim)

Cosine similarities: tensor([-0.1116, -0.0604,  0.1709])
Using F.cosine_similarity: tensor([-0.1116, -0.0604,  0.1709])


# 12. Best Practices and Common Pitfalls

In [17]:
# Pitfall 1: In-place operations breaking the computation graph
x = torch.tensor([2.0], requires_grad=True)
y = x * 2

# This works fine
z = y + 3
z.backward()
print("Gradient (normal):", x.grad)

# Pitfall: In-place operations can cause issues
x = torch.tensor([2.0], requires_grad=True)
y = x * 2
y += 3  # In-place operation
# y.backward()  # This might cause an error!

print("\nIn-place operations can break gradient computation!")
print("Use non-inplace operations when possible during training")

Gradient (normal): tensor([2.])

In-place operations can break gradient computation!
Use non-inplace operations when possible during training


In [18]:
# Pitfall 2: Forgetting to zero gradients
x = torch.tensor([2.0], requires_grad=True)

for i in range(3):
    y = x * (i + 1)
    y.backward()
    print(f"Iteration {i}: gradient = {x.grad.item()}")
    # x.grad.zero_()  # Uncomment to fix!

print("\nGradients accumulate across backward passes!")
print("Always zero gradients before each optimization step")

Iteration 0: gradient = 1.0
Iteration 1: gradient = 3.0
Iteration 2: gradient = 6.0

Gradients accumulate across backward passes!
Always zero gradients before each optimization step


In [19]:
# Pitfall 3: CPU-GPU mismatch
x_cpu = torch.randn(3, 3)
y_gpu = torch.randn(3, 3, device='cuda')

try:
    z = x_cpu + y_gpu
except RuntimeError as e:
    print("Error:", e)
    print("\nTensors must be on the same device!")
    print("Solution: Move both to same device")

Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Tensors must be on the same device!
Solution: Move both to same device


In [20]:
# Pitfall 4: Shape mismatch in matrix multiplication
A = torch.randn(2, 3)
B = torch.randn(4, 5)

try:
    C = torch.matmul(A, B)
except RuntimeError as e:
    print("Error:", e)
    print("\nInner dimensions must match for matrix multiplication!")
    print("A: (2, 3), B: (4, 5)")
    print("Need A: (2, k), B: (k, 5)")

Error: mat1 and mat2 shapes cannot be multiplied (2x3 and 4x5)

Inner dimensions must match for matrix multiplication!
A: (2, 3), B: (4, 5)
Need A: (2, k), B: (k, 5)


In [21]:
# Best Practice 1: Use appropriate data types
# Float32 is standard for deep learning
x_float32 = torch.randn(1000, 1000, dtype=torch.float32)
x_float64 = torch.randn(1000, 1000, dtype=torch.float64)

print(f"Float32 memory: {x_float32.element_size() * x_float32.numel() / 1024**2:.2f} MB")
print(f"Float64 memory: {x_float64.element_size() * x_float64.numel() / 1024**2:.2f} MB")

print("\nUse float32 for most ML tasks to save memory and compute")

Float32 memory: 3.81 MB
Float64 memory: 7.63 MB

Use float32 for most ML tasks to save memory and compute


In [22]:
# Best Practice 2: Pin memory for faster GPU transfer
if torch.cuda.is_available():
    # Pinned memory tensors transfer faster to GPU
    x_pinned = torch.randn(1000, 1000, pin_memory=True)
    x_regular = torch.randn(1000, 1000)
    
    print("Pinned memory enables faster CPU-to-GPU transfers")
    print("Use pin_memory=True when loading data for GPU training")

Pinned memory enables faster CPU-to-GPU transfers
Use pin_memory=True when loading data for GPU training


# 13. Practice Exercises

Test your understanding with these exercises.

In [23]:
# Exercise 1: Tensor Creation
# Create a tensor with values from 0 to 99, reshape it to 10x10, and calculate its mean

# Your code here:
# tensor = torch.arange(100).reshape(10, 10)
# print(tensor)
# print("Mean:", tensor.mean())

# Solution (uncomment to check):
tensor = torch.arange(100).reshape(10, 10)
print("Tensor:\n", tensor)
print("Mean:", tensor.mean())

Tensor:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [24]:
# Exercise 2: Broadcasting
# Add a 1D tensor of shape (3,) to a 2D tensor of shape (2,3) without reshaping

# Your code here:
# a = torch.tensor([1, 2, 3])
# b = torch.tensor([[4, 5, 6], [7, 8, 9]])
# result = a + b
# print(result)

# Solution:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[4, 5, 6], [7, 8, 9]])
result = a + b
print("Result of broadcasting:\n", result)

Result of broadcasting:
 tensor([[ 5,  7,  9],
        [ 8, 10, 12]])


In [25]:
# Exercise 3: Matrix Operations
# Create two 3x3 matrices, compute their dot product, transpose, and find the inverse

# Your code here:
# A = torch.randn(3, 3)
# B = torch.randn(3, 3)
# dot_product = torch.matmul(A, B)
# transpose = A.T
# inverse = torch.inverse(A)

# Solution:
A = torch.randn(3, 3)
B = torch.randn(3, 3)
print("A:\n", A)
print("B:\n", B)
print("\nDot product (A @ B):\n", torch.matmul(A, B))
print("\nTranspose of A:\n", A.T)
print("\nInverse of A:\n", torch.inverse(A))

A:
 tensor([[-2.4648,  0.8626,  0.8615],
        [-0.3565,  0.2593,  2.1632],
        [ 0.5344, -1.2394, -0.4458]])
B:
 tensor([[-0.7860, -0.4456, -1.1582],
        [-0.0899,  0.8923, -0.2467],
        [ 0.6978, -0.7475,  0.4751]])

Dot product (A @ B):
 tensor([[ 2.4610,  1.2240,  3.0513],
        [ 1.7664, -1.2269,  1.3767],
        [-0.6197, -1.0108, -0.5249]])

Transpose of A:
 tensor([[-2.4648, -0.3565,  0.5344],
        [ 0.8626,  0.2593, -1.2394],
        [ 0.8615,  2.1632, -0.4458]])

Inverse of A:
 tensor([[-0.4932,  0.1313, -0.3158],
        [-0.1917, -0.1227, -0.9659],
        [-0.0583,  0.4986,  0.0637]])


In [26]:
# Exercise 4: Indexing
# Extract all even numbers from a tensor and replace odd numbers with 0

# Your code here:
# x = torch.arange(20)
# # Extract evens
# evens = x[x % 2 == 0]
# # Replace odds with 0
# x[x % 2 != 0] = 0

# Solution:
x = torch.arange(20)
print("Original:", x)
evens = x[x % 2 == 0]
print("Even numbers:", evens)
x[x % 2 != 0] = 0
print("After replacing odds with 0:", x)

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
Even numbers: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
After replacing odds with 0: tensor([ 0,  0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
        18,  0])


In [27]:
# Exercise 5: Gradient Computation
# Compute the gradient of f(x) = x^3 + 2x^2 + x at x = 2

# Your code here:
# x = torch.tensor([2.0], requires_grad=True)
# y = x**3 + 2*x**2 + x
# y.backward()
# print(f"Gradient at x=2: {x.grad.item()}")

# Solution:
x = torch.tensor([2.0], requires_grad=True)
y = x**3 + 2*x**2 + x
y.backward()
print(f"Gradient at x=2: {x.grad.item()}")
print("Manual verification: df/dx = 3x^2 + 4x + 1 = 3(4) + 4(2) + 1 = 21")

Gradient at x=2: 21.0
Manual verification: df/dx = 3x^2 + 4x + 1 = 3(4) + 4(2) + 1 = 21


In [28]:
# Exercise 6: Reshaping Challenge
# Convert a tensor of shape (2, 3, 4) to shape (6, 4) using reshape

# Your code here:
# x = torch.randn(2, 3, 4)
# reshaped = x.reshape(6, 4)
# print(f"Original shape: {x.shape}")
# print(f"Reshaped: {reshaped.shape}")

# Solution:
x = torch.randn(2, 3, 4)
print(f"Original shape: {x.shape}")
reshaped = x.reshape(6, 4)
print(f"Reshaped shape: {reshaped.shape}")
print("Verification: 2*3*4 = 24, 6*4 = 24 ✓")

Original shape: torch.Size([2, 3, 4])
Reshaped shape: torch.Size([6, 4])
Verification: 2*3*4 = 24, 6*4 = 24 ✓


In [29]:
# Exercise 7: Normalization
# Implement min-max normalization: (x - min) / (max - min)

# Your code here:
# x = torch.randn(5, 5)
# x_min = x.min()
# x_max = x.max()
# normalized = (x - x_min) / (x_max - x_min)

# Solution:
x = torch.randn(5, 5)
print("Original:\n", x)
x_min = x.min()
x_max = x.max()
normalized = (x - x_min) / (x_max - x_min)
print("\nNormalized (0-1 range):\n", normalized)
print(f"Min: {normalized.min().item()}, Max: {normalized.max().item()}")

Original:
 tensor([[-0.9003, -0.5177,  1.2262,  0.1402, -1.9315],
        [-0.2737, -0.4638,  0.0417,  2.2286, -0.3645],
        [-0.2627, -0.9941,  0.6491,  1.9607,  0.8298],
        [ 0.8636,  0.4430,  0.5660, -0.0597,  0.5360],
        [-0.3969,  0.4869,  0.2517, -0.1258,  0.4963]])

Normalized (0-1 range):
 tensor([[0.2479, 0.3399, 0.7591, 0.4980, 0.0000],
        [0.3985, 0.3528, 0.4743, 1.0000, 0.3767],
        [0.4012, 0.2253, 0.6203, 0.9356, 0.6638],
        [0.6719, 0.5708, 0.6003, 0.4500, 0.5931],
        [0.3689, 0.5813, 0.5248, 0.4341, 0.5836]])
Min: 0.0, Max: 1.0


# Summary: Key Takeaways

## Tensor Fundamentals ✓
- **Tensors** are multi-dimensional arrays (scalars, vectors, matrices, higher-dim)
- **Creation**: `torch.tensor()`, `torch.zeros()`, `torch.ones()`, `torch.rand()`, `torch.arange()`, etc.
- **Properties**: shape, dtype, device, numel, ndim

## Operations ✓
- **Arithmetic**: +, -, *, /, ** (element-wise)
- **Matrix operations**: `@`, `torch.matmul()`, `.T`, `torch.inverse()`, `torch.det()`
- **Aggregation**: `.sum()`, `.mean()`, `.min()`, `.max()`, `.std()`

## Manipulation ✓
- **Reshaping**: `.reshape()`, `.view()`, `.flatten()`, `.squeeze()`, `.unsqueeze()`
- **Permutation**: `.permute()`, `.transpose()`
- **Broadcasting**: Automatic dimension expansion for operations

## Advanced Features ✓
- **Indexing**: Slicing, boolean masking, advanced indexing
- **GPU**: `.to('cuda')`, `.cuda()` for faster computation
- **Autograd**: Automatic differentiation with `requires_grad=True`

## Best Practices ✓
- Use appropriate dtypes (float32 for ML)
- Zero gradients before each backward pass
- Avoid in-place operations during training
- Ensure tensors are on same device for operations

## Next Steps
- Practice with real datasets
- Build simple neural networks
- Explore PyTorch's nn.Module
- Learn about optimizers and loss functions